/*
 * furstenberg_orbits.c — Phase 1 for Furstenberg's ×2, ×3 conjecture
 *
 * For each prime p (coprime to 6) up to P_MAX, computes:
 *   - ord_p(2), ord_p(3), and |⟨2,3⟩| = lcm(ord_p(2), ord_p(3))
 *   - Whether ⟨2,3⟩ = (Z/pZ)* (Furstenberg holds at finite scale p)
 *   - The index (p-1)/|⟨2,3⟩| when generation fails
 *
 * Also computes CF convergents of log₂3 and multi-scale resonant fractions.
 *
 * In a cyclic group G = (Z/pZ)*, the subgroup generated by two elements
 * satisfies |⟨a,b⟩| = lcm(ord(a), ord(b)).  So Furstenberg at scale p
 * reduces to: does lcm(ord_p(2), ord_p(3)) = p-1?
 *
 * Usage:
 *   ./furstenberg_orbits P_MAX              Prime scan up to P_MAX
 *   ./furstenberg_orbits --resume P_MAX     Resume from checkpoint
 *   ./furstenberg_orbits --convergents      CF convergents of log₂3
 *
 * Output CSVs:
 *   furstenberg_primes.csv       Per-prime results (exceptional primes only)
 *   furstenberg_summary.csv      Aggregated statistics by decade
 *   furstenberg_convergents.csv  CF convergents of log₂3
 *
 * Build: make furstenberg
 *
 * OpenMP: 24 threads, parallelize over prime chunks.
 * Checkpoint: binary state file, atomic rename, every 100K primes.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include <inttypes.h>
#include <omp.h>
#include <time.h>

/* ═══════════════════════════════════════════════════════════════════
 * Constants
 * ═══════════════════════════════════════════════════════════════════ */

#define LOG2_3  1.5849625007211561814537389439478165286L

#define MAX_FACTORS       20    /* max distinct prime factors of p-1       */
#define CHUNK_SIZE     50000    /* primes per parallel chunk               */
#define CHECKPOINT_INTERVAL 4   /* chunks between checkpoints (200K primes)*/
#define NUM_DECADES       10    /* summary bins: [5,10), [10,100), ...     */
#define MAX_INDEX_HIST    32    /* histogram bins for index distribution   */
#define MAX_CF_TERMS      60    /* continued fraction terms for log₂3     */

static const char *PRIMES_CSV  = "furstenberg_primes.csv";
static const char *SUMMARY_CSV = "furstenberg_summary.csv";
static const char *CONV_CSV    = "furstenberg_convergents.csv";
static const char *CKPT_FILE   = "furstenberg_state.bin";

static int min_index_csv = 2;  /* only write primes with index >= this to CSV */

/* ═══════════════════════════════════════════════════════════════════
 * Modular arithmetic (128-bit intermediate)
 * ═══════════════════════════════════════════════════════════════════ */

static inline uint64_t mulmod(uint64_t a, uint64_t b, uint64_t m) {
    return (unsigned __int128)a * b % m;
}

static uint64_t powmod(uint64_t base, uint64_t exp, uint64_t mod) {
    uint64_t r = 1;
    base %= mod;
    while (exp > 0) {
        if (exp & 1) r = mulmod(r, base, mod);
        base = mulmod(base, base, mod);
        exp >>= 1;
    }
    return r;
}

static uint64_t gcd(uint64_t a, uint64_t b) {
    while (b) { uint64_t t = b; b = a % b; a = t; }
    return a;
}

/* ═══════════════════════════════════════════════════════════════════
 * Factorization by trial division
 * ═══════════════════════════════════════════════════════════════════ */

typedef struct {
    uint64_t p[MAX_FACTORS];
    int      e[MAX_FACTORS];
    int      nf;
} Factors;

/* Small primes up to 10^5, enough to factor numbers up to 10^10 */
static uint32_t sprimes[10000];
static int      nsprimes = 0;

static void init_small_primes(void) {
    sprimes[nsprimes++] = 2;
    for (uint32_t i = 3; i <= 100000; i += 2) {
        int comp = 0;
        for (int j = 0; j < nsprimes && (uint64_t)sprimes[j] * sprimes[j] <= i; j++)
            if (i % sprimes[j] == 0) { comp = 1; break; }
        if (!comp) sprimes[nsprimes++] = i;
    }
}

static void factorize(uint64_t n, Factors *f) {
    f->nf = 0;
    for (int i = 0; i < nsprimes && (uint64_t)sprimes[i] * sprimes[i] <= n; i++) {
        uint64_t q = sprimes[i];
        if (n % q == 0) {
            f->p[f->nf] = q;
            f->e[f->nf] = 0;
            while (n % q == 0) { f->e[f->nf]++; n /= q; }
            f->nf++;
        }
    }
    if (n > 1) {
        f->p[f->nf] = n;
        f->e[f->nf] = 1;
        f->nf++;
    }
}

/* ═══════════════════════════════════════════════════════════════════
 * Multiplicative order: ord_p(x) given factorization of p-1
 *
 * Algorithm: start with ord = p-1, then for each prime factor q
 * of p-1, divide out q while x^(ord/q) ≡ 1 (mod p).
 * ═══════════════════════════════════════════════════════════════════ */

static uint64_t mult_order(uint64_t x, uint64_t p, const Factors *f_pm1) {
    uint64_t ord = p - 1;
    for (int i = 0; i < f_pm1->nf; i++) {
        uint64_t q = f_pm1->p[i];
        while (ord % q == 0 && powmod(x, ord / q, p) == 1)
            ord /= q;
    }
    return ord;
}

/* ═══════════════════════════════════════════════════════════════════
 * Prime sieve (bit-packed, odd numbers only)
 * Bit i represents number 2i+3.  Set bit = composite.
 * ═══════════════════════════════════════════════════════════════════ */

static uint8_t *sieve = NULL;
static uint64_t sieve_max = 0;

#define SIEVE_IDX(n)   (((n) - 3) >> 1)
#define SIEVE_IS_COMP(n) (sieve[SIEVE_IDX(n) >> 3] & (1u << (SIEVE_IDX(n) & 7)))
#define SIEVE_MARK(n)    (sieve[SIEVE_IDX(n) >> 3] |= (1u << (SIEVE_IDX(n) & 7)))

static void generate_sieve(uint64_t limit) {
    sieve_max = limit;
    uint64_t nbytes = (limit / 2 + 8) / 8 + 1;
    sieve = calloc(nbytes, 1);
    if (!sieve) { fprintf(stderr, "OOM: sieve needs %"PRIu64" bytes\n", nbytes); exit(1); }

    uint64_t sq = (uint64_t)sqrt((double)limit) + 1;
    for (uint64_t i = 3; i <= sq; i += 2) {
        if (!SIEVE_IS_COMP(i)) {
            for (uint64_t j = i * i; j <= limit; j += 2 * i)
                SIEVE_MARK(j);
        }
    }
}

static inline int is_prime_sieve(uint64_t n) {
    if (n == 2) return 1;
    if (n < 3 || n % 2 == 0) return 0;
    return !SIEVE_IS_COMP(n);
}

/* ═══════════════════════════════════════════════════════════════════
 * Collect all primes coprime to 6 up to P_MAX into an array
 * ═══════════════════════════════════════════════════════════════════ */

static uint64_t *prime_list = NULL;
static uint64_t  num_primes = 0;

static void collect_primes(uint64_t pmax) {
    /* Count first */
    uint64_t count = 0;
    for (uint64_t p = 5; p <= pmax; p += 2)
        if (p % 3 != 0 && is_prime_sieve(p)) count++;

    prime_list = malloc(count * sizeof(uint64_t));
    if (!prime_list) { fprintf(stderr, "OOM: prime list\n"); exit(1); }

    num_primes = 0;
    for (uint64_t p = 5; p <= pmax; p += 2)
        if (p % 3 != 0 && is_prime_sieve(p))
            prime_list[num_primes++] = p;

    printf("  Collected %"PRIu64" primes coprime to 6 in [5, %"PRIu64"]\n",
           num_primes, pmax);
}

/* ═══════════════════════════════════════════════════════════════════
 * Per-prime result (kept small for cache efficiency)
 * ═══════════════════════════════════════════════════════════════════ */

typedef struct {
    uint64_t p;
    uint64_t ord2;
    uint64_t ord3;
    uint64_t lcm_ord;     /* = |⟨2,3⟩| = lcm(ord2, ord3) */
    uint64_t index;       /* = (p-1) / lcm_ord            */
} PrimeResult;

/* ═══════════════════════════════════════════════════════════════════
 * Summary statistics per decade [10^k, 10^{k+1})
 * ═══════════════════════════════════════════════════════════════════ */

typedef struct {
    uint64_t lo, hi;
    uint64_t n_primes;
    uint64_t n_full;          /* ⟨2,3⟩ = (Z/pZ)* */
    uint64_t n_index2;        /* index exactly 2  */
    uint64_t n_index_other;   /* index > 2        */
    uint64_t max_index;
    double   min_fraction;
    double   sum_fraction;
    uint64_t index_hist[MAX_INDEX_HIST]; /* count by index value */
} DecadeSummary;

static DecadeSummary decades[NUM_DECADES];

static void init_decades(void) {
    uint64_t lo = 5;
    for (int i = 0; i < NUM_DECADES; i++) {
        uint64_t hi = (i == 0) ? 100 : lo * 10;
        decades[i].lo = lo;
        decades[i].hi = hi;
        decades[i].n_primes = 0;
        decades[i].n_full = 0;
        decades[i].n_index2 = 0;
        decades[i].n_index_other = 0;
        decades[i].max_index = 0;
        decades[i].min_fraction = 1.0;
        decades[i].sum_fraction = 0.0;
        memset(decades[i].index_hist, 0, sizeof(decades[i].index_hist));
        lo = hi;
    }
}

static int decade_bin(uint64_t p) {
    if (p < 100) return 0;
    int bin = (int)floor(log10((double)p));
    if (bin < 2) bin = 2;
    if (bin >= NUM_DECADES + 1) bin = NUM_DECADES;
    return bin - 1;
}

/* ═══════════════════════════════════════════════════════════════════
 * Checkpoint state
 * ═══════════════════════════════════════════════════════════════════ */

typedef struct {
    uint64_t magic;          /* 0x4655525354454E42 "FURSTENB" */
    uint64_t chunk_done;     /* number of chunks completed     */
    uint64_t primes_done;    /* total primes processed         */
    DecadeSummary decades[NUM_DECADES];
} Checkpoint;

#define CKPT_MAGIC 0x4655525354454E42ULL

static void save_checkpoint(uint64_t chunk_done, uint64_t primes_done) {
    Checkpoint ck;
    ck.magic = CKPT_MAGIC;
    ck.chunk_done = chunk_done;
    ck.primes_done = primes_done;
    memcpy(ck.decades, decades, sizeof(decades));

    char tmp[256];
    snprintf(tmp, sizeof(tmp), "%s.tmp", CKPT_FILE);
    FILE *f = fopen(tmp, "wb");
    if (!f) return;
    fwrite(&ck, sizeof(ck), 1, f);
    fclose(f);
    rename(tmp, CKPT_FILE);
}

static int load_checkpoint(Checkpoint *ck) {
    FILE *f = fopen(CKPT_FILE, "rb");
    if (!f) return 0;
    size_t r = fread(ck, sizeof(*ck), 1, f);
    fclose(f);
    return (r == 1 && ck->magic == CKPT_MAGIC);
}

/* ═══════════════════════════════════════════════════════════════════
 * CF convergents of log₂3
 * ═══════════════════════════════════════════════════════════════════ */

static void compute_convergents(void) {
    printf("\n=== CF Convergents of log₂3 ===\n\n");

    FILE *csv = fopen(CONV_CSV, "w");
    if (!csv) { perror(CONV_CSV); return; }
    fprintf(csv, "n,cf_coeff,p_n,q_n,cell_error,abs_error,log10_error,"
                 "ratio_to_baker\n");

    /* Use long double for precision */
    long double alpha = LOG2_3;
    int64_t p_prev = 1, p_curr = 1;   /* p_{-1} = 1, p_0 = a_0 = 1 */
    int64_t q_prev = 0, q_curr = 1;   /* q_{-1} = 0, q_0 = 1       */

    /* a_0 = floor(log₂3) = 1 */
    int64_t a0 = (int64_t)floorl(alpha);
    p_curr = a0;
    q_curr = 1;

    long double err = fabsl((long double)p_curr - LOG2_3 * (long double)q_curr);
    printf("n=%2d  a=%3"PRId64"  p/q = %12"PRId64" / %-12"PRId64
           "  |cellError| = %.6Le\n", 0, a0, p_curr, q_curr, err);
    fprintf(csv, "0,%"PRId64",%"PRId64",%"PRId64",%.15Le,%.15Le,%.6f,0.0\n",
            a0, p_curr, q_curr,
            (long double)p_curr - LOG2_3 * (long double)q_curr,
            err, (double)log10l(err));

    alpha = 1.0L / (alpha - (long double)a0);
    p_prev = 1; /* p_{-1} */
    /* q_prev = 0 stays */

    for (int n = 1; n < MAX_CF_TERMS; n++) {
        int64_t a = (int64_t)floorl(alpha);
        int64_t p_next = a * p_curr + p_prev;
        int64_t q_next = a * q_curr + q_prev;

        if (q_next < 0 || p_next < 0) break;  /* overflow */

        err = fabsl((long double)p_next - LOG2_3 * (long double)q_next);

        /* Baker lower bound estimate: C / q^κ.  Use κ ≈ 5.125 (Rhin) */
        long double baker_est = 1.0L / powl((long double)q_next, 5.125L);
        long double ratio = (baker_est > 0) ? err / baker_est : 0;

        printf("n=%2d  a=%3"PRId64"  p/q = %12"PRId64" / %-12"PRId64
               "  |cellError| = %.6Le  (err/Baker ~ %.2Lf)\n",
               n, a, p_next, q_next, err, ratio);

        fprintf(csv, "%d,%"PRId64",%"PRId64",%"PRId64",%.15Le,%.15Le,%.6f,%.6Lf\n",
                n, a, p_next, q_next,
                (long double)p_next - LOG2_3 * (long double)q_next,
                err, (err > 0 ? (double)log10l(err) : -999.0), ratio);

        p_prev = p_curr; p_curr = p_next;
        q_prev = q_curr; q_curr = q_next;

        long double frac = alpha - (long double)a;
        if (frac < 1e-15L) break;
        alpha = 1.0L / frac;
    }

    fclose(csv);
    printf("\n  Written to %s\n", CONV_CSV);
}

/* ═══════════════════════════════════════════════════════════════════
 * Multi-scale resonant fraction
 *
 * For each scale N, count pairs (a,b) with 0 ≤ b < N, a = round(log₂3·b),
 * 0 ≤ a < N, and |a - log₂3·b| < threshold.
 *
 * Also count using modular resonance: 2^a ≡ 3^b (mod N) for
 * various N coprime to 6.
 * ═══════════════════════════════════════════════════════════════════ */

static void compute_multiscale(void) {
    printf("\n=== Multi-scale Resonant Fractions ===\n\n");

    printf("  %-8s  %-12s  %-8s  %-10s  %-12s  %-10s\n",
           "k", "N=6^k", "res_cnt", "res_frac", "mod_res_cnt", "contraction");
    printf("  %-8s  %-12s  %-8s  %-10s  %-12s  %-10s\n",
           "--------", "------------", "--------", "----------",
           "------------", "----------");

    double prev_frac = 0;

    for (int k = 1; k <= 12; k++) {
        uint64_t N = 1;
        for (int i = 0; i < k; i++) {
            if (N > UINT64_MAX / 6) goto done_multiscale;
            N *= 6;
        }

        /* CellError resonance: |a - log₂3·b| < 1/N */
        double threshold = 1.0 / (double)N;
        uint64_t ce_count = 0;

        /* For large N, parallelize over b */
        #pragma omp parallel for reduction(+:ce_count) schedule(static)
        for (int64_t b = 0; b < (int64_t)N; b++) {
            long double target = LOG2_3 * (long double)b;
            int64_t a = (int64_t)roundl(target);
            if (a >= 0 && a < (int64_t)N) {
                long double err = fabsl((long double)a - target);
                if (err < threshold)
                    ce_count++;
            }
        }

        /* Modular resonance: 2^a ≡ 3^b (mod N) for a,b in [0, ord) */
        /* Only meaningful when gcd(N, 6) = 1; skip for N = 6^k    */
        /* Instead, use a nearby prime for the modular test          */
        uint64_t mod_count = 0;
        uint64_t mod_N = N + 1;  /* find a prime near N coprime to 6 */
        while (mod_N < N + 10000) {
            if (mod_N % 2 != 0 && mod_N % 3 != 0 && mod_N > 4) {
                /* Quick primality check for small values */
                int is_p = 1;
                for (uint64_t d = 5; d * d <= mod_N; d += 2)
                    if (mod_N % d == 0) { is_p = 0; break; }
                if (is_p) break;
            }
            mod_N++;
        }

        if (mod_N < N + 10000) {
            /* Count (a,b) in [0, ord_2)×[0, ord_3) with 2^a ≡ 3^b (mod mod_N) */
            /* Using precomputed powers */
            Factors f_pm1;
            factorize(mod_N - 1, &f_pm1);
            uint64_t o2 = mult_order(2, mod_N, &f_pm1);
            uint64_t o3 = mult_order(3, mod_N, &f_pm1);
            /* In (Z/mod_N Z)*, ⟨2⟩ has o2 elements, ⟨3⟩ has o3 elements.
             * |⟨2,3⟩| = lcm(o2, o3).  The number of (a,b) pairs with
             * 2^a = 3^b is |⟨2⟩ ∩ ⟨3⟩| = gcd(o2, o3). */
            mod_count = gcd(o2, o3);
        }

        double frac = (double)ce_count / (double)N;
        double contraction = (prev_frac > 0) ? frac / prev_frac : 0;

        printf("  %-8d  %-12"PRIu64"  %-8"PRIu64"  %-10.6f  %-12"PRIu64"  %-10.4f\n",
               k, N, ce_count, frac, mod_count, contraction);

        prev_frac = frac;

        /* Don't go beyond N where the loop takes too long */
        if (N > 1000000000ULL) break;
    }
done_multiscale:
    printf("\n");
}

/* ═══════════════════════════════════════════════════════════════════
 * Main prime scan
 * ═══════════════════════════════════════════════════════════════════ */

static void run_prime_scan(uint64_t pmax, int resume) {
    printf("\n=== Furstenberg ×2, ×3 Prime Scan ===\n");
    printf("  P_MAX = %"PRIu64"  (%d threads)  min_index_csv = %d\n\n",
           pmax, omp_get_max_threads(), min_index_csv);

    /* 1. Sieve */
    printf("  Sieving primes up to %"PRIu64"...\n", pmax);
    double t0 = omp_get_wtime();
    generate_sieve(pmax);
    printf("  Sieve: %.2f s, %.1f MB\n",
           omp_get_wtime() - t0, (double)(pmax / 2 / 8 + 1) / 1e6);

    /* 2. Collect primes coprime to 6 */
    collect_primes(pmax);

    /* 3. Initialize summaries */
    init_decades();

    /* 4. Resume from checkpoint? */
    uint64_t start_chunk = 0;
    uint64_t primes_done = 0;

    if (resume) {
        Checkpoint ck;
        if (load_checkpoint(&ck)) {
            start_chunk = ck.chunk_done;
            primes_done = ck.primes_done;
            memcpy(decades, ck.decades, sizeof(decades));
            printf("  Resumed from checkpoint: %"PRIu64" primes, chunk %"PRIu64"\n",
                   primes_done, start_chunk);
        } else {
            printf("  No checkpoint found, starting fresh.\n");
        }
    }

    /* 5. Open primes CSV (exceptional primes only — full gen skipped) */
    FILE *csv = fopen(PRIMES_CSV, start_chunk > 0 ? "a" : "w");
    if (!csv) { perror(PRIMES_CSV); return; }
    if (start_chunk == 0) {
        fprintf(csv, "p,p_minus_1,ord2,ord3,lcm_ord,index,fraction\n");
    }

    /* 6. Process in chunks */
    uint64_t total_chunks = (num_primes + CHUNK_SIZE - 1) / CHUNK_SIZE;
    PrimeResult *results = malloc(CHUNK_SIZE * sizeof(PrimeResult));
    if (!results) { fprintf(stderr, "OOM: results\n"); fclose(csv); return; }

    /* Thread-local decade accumulators (avoid false sharing) */
    int nthreads = omp_get_max_threads();
    DecadeSummary (*local_decades)[NUM_DECADES] =
        calloc(nthreads, sizeof(DecadeSummary[NUM_DECADES]));

    double t_start = omp_get_wtime();
    uint64_t exceptional_count = 0;

    for (uint64_t chunk = start_chunk; chunk < total_chunks; chunk++) {
        uint64_t i_start = chunk * CHUNK_SIZE;
        uint64_t i_end = i_start + CHUNK_SIZE;
        if (i_end > num_primes) i_end = num_primes;
        uint64_t chunk_len = i_end - i_start;

        /* Clear local accumulators */
        memset(local_decades, 0, nthreads * sizeof(DecadeSummary[NUM_DECADES]));

        /* Parallel computation */
        #pragma omp parallel for schedule(dynamic, 200)
        for (uint64_t i = i_start; i < i_end; i++) {
            uint64_t p = prime_list[i];
            int tid = omp_get_thread_num();

            /* Factor p-1 */
            Factors f;
            factorize(p - 1, &f);

            /* Multiplicative orders */
            uint64_t o2 = mult_order(2, p, &f);
            uint64_t o3 = mult_order(3, p, &f);
            uint64_t g = gcd(o2, o3);
            uint64_t lcm_o = o2 / g * o3;   /* lcm avoiding overflow */
            uint64_t idx = (p - 1) / lcm_o;

            /* Store result */
            uint64_t ri = i - i_start;
            results[ri].p = p;
            results[ri].ord2 = o2;
            results[ri].ord3 = o3;
            results[ri].lcm_ord = lcm_o;
            results[ri].index = idx;

            /* Accumulate into thread-local decade summary */
            int bin = decade_bin(p);
            if (bin >= 0 && bin < NUM_DECADES) {
                DecadeSummary *ds = &local_decades[tid][bin];
                ds->n_primes++;
                double frac = (double)lcm_o / (double)(p - 1);
                ds->sum_fraction += frac;
                if (frac < ds->min_fraction || ds->min_fraction == 0)
                    ds->min_fraction = frac;

                if (idx == 1) {
                    ds->n_full++;
                } else if (idx == 2) {
                    ds->n_index2++;
                } else {
                    ds->n_index_other++;
                }
                if (idx > ds->max_index)
                    ds->max_index = idx;
                if (idx <= MAX_INDEX_HIST)
                    ds->index_hist[idx - 1]++;
            }
        }

        /* Merge thread-local into global */
        for (int t = 0; t < nthreads; t++) {
            for (int b = 0; b < NUM_DECADES; b++) {
                DecadeSummary *g = &decades[b];
                DecadeSummary *l = &local_decades[t][b];
                g->n_primes += l->n_primes;
                g->n_full   += l->n_full;
                g->n_index2 += l->n_index2;
                g->n_index_other += l->n_index_other;
                g->sum_fraction += l->sum_fraction;
                if (l->min_fraction > 0 &&
                    (l->min_fraction < g->min_fraction || g->min_fraction == 0))
                    g->min_fraction = l->min_fraction;
                if (l->max_index > g->max_index)
                    g->max_index = l->max_index;
                for (int h = 0; h < MAX_INDEX_HIST; h++)
                    g->index_hist[h] += l->index_hist[h];
            }
        }

        /* Write exceptional primes to CSV (filtered by min_index_csv) */
        for (uint64_t ri = 0; ri < chunk_len; ri++) {
            if (results[ri].index >= (uint64_t)min_index_csv) {
                fprintf(csv, "%"PRIu64",%"PRIu64",%"PRIu64",%"PRIu64
                        ",%"PRIu64",%"PRIu64",%.10f\n",
                        results[ri].p,
                        results[ri].p - 1,
                        results[ri].ord2,
                        results[ri].ord3,
                        results[ri].lcm_ord,
                        results[ri].index,
                        (double)results[ri].lcm_ord / (double)(results[ri].p - 1));
                exceptional_count++;
            }
        }

        primes_done = i_end;

        /* Progress report */
        if (chunk % 4 == 0 || chunk == total_chunks - 1) {
            double elapsed = omp_get_wtime() - t_start;
            double rate = (double)(primes_done - start_chunk * CHUNK_SIZE) / elapsed;
            uint64_t total_full = 0, total_exc = 0, total_n = 0;
            for (int b = 0; b < NUM_DECADES; b++) {
                total_full += decades[b].n_full;
                total_exc  += decades[b].n_index2 + decades[b].n_index_other;
                total_n    += decades[b].n_primes;
            }
            printf("  [%6.1f s]  %"PRIu64"/%"PRIu64" primes  "
                   "(%.0f/s)  full_gen=%"PRIu64" (%.2f%%)  exc=%"PRIu64"\n",
                   elapsed, primes_done, num_primes, rate,
                   total_full,
                   total_n > 0 ? 100.0 * total_full / total_n : 0,
                   total_exc);
        }

        /* Checkpoint */
        if ((chunk + 1) % CHECKPOINT_INTERVAL == 0) {
            fflush(csv);
            save_checkpoint(chunk + 1, primes_done);
        }
    }

    fflush(csv);
    fclose(csv);
    free(results);
    free(local_decades);

    double elapsed = omp_get_wtime() - t_start;
    printf("\n  Scan complete: %"PRIu64" primes in %.2f s (%.0f primes/s)\n",
           num_primes, elapsed, num_primes / elapsed);
    printf("  Exceptional primes written: %"PRIu64"\n", exceptional_count);

    /* 7. Write summary CSV */
    FILE *sf = fopen(SUMMARY_CSV, "w");
    if (!sf) { perror(SUMMARY_CSV); return; }
    fprintf(sf, "range_lo,range_hi,n_primes,n_full,pct_full,"
                "n_index2,n_index_gt2,max_index,avg_fraction,min_fraction\n");

    printf("\n  === Summary by Decade ===\n\n");
    printf("  %-14s  %8s  %8s  %7s  %6s  %6s  %6s  %10s\n",
           "Range", "Primes", "FullGen", "Pct", "Idx=2", "Idx>2",
           "MaxIdx", "MinFrac");
    printf("  %-14s  %8s  %8s  %7s  %6s  %6s  %6s  %10s\n",
           "--------------", "--------", "--------", "-------",
           "------", "------", "------", "----------");

    for (int b = 0; b < NUM_DECADES; b++) {
        DecadeSummary *d = &decades[b];
        if (d->n_primes == 0) continue;

        double pct = 100.0 * d->n_full / d->n_primes;
        double avg = d->sum_fraction / d->n_primes;

        printf("  [%6"PRIu64", %6"PRIu64")  %8"PRIu64"  %8"PRIu64"  %6.2f%%  "
               "%6"PRIu64"  %6"PRIu64"  %6"PRIu64"  %10.8f\n",
               d->lo, d->hi, d->n_primes, d->n_full, pct,
               d->n_index2, d->n_index_other, d->max_index, d->min_fraction);

        fprintf(sf, "%"PRIu64",%"PRIu64",%"PRIu64",%"PRIu64",%.6f,"
                    "%"PRIu64",%"PRIu64",%"PRIu64",%.10f,%.10f\n",
                d->lo, d->hi, d->n_primes, d->n_full, pct / 100.0,
                d->n_index2, d->n_index_other, d->max_index,
                avg, d->min_fraction);
    }

    /* Index distribution */
    printf("\n  === Index Distribution (all primes) ===\n\n");
    printf("  %6s  %10s  %8s\n", "Index", "Count", "Pct");
    printf("  %6s  %10s  %8s\n", "------", "----------", "--------");

    uint64_t total_primes_all = 0;
    for (int b = 0; b < NUM_DECADES; b++)
        total_primes_all += decades[b].n_primes;

    for (int h = 0; h < MAX_INDEX_HIST; h++) {
        uint64_t cnt = 0;
        for (int b = 0; b < NUM_DECADES; b++)
            cnt += decades[b].index_hist[h];
        if (cnt > 0)
            printf("  %6d  %10"PRIu64"  %7.3f%%\n",
                   h + 1, cnt, 100.0 * cnt / total_primes_all);
    }

    /* Exceptional primes: those with index > 2 */
    printf("\n  === Exceptional Primes with Large Index (sample) ===\n\n");

    /* Re-scan for display: find primes with largest indices */
    /* (Already written to CSV, just report the decades summary) */
    for (int b = 0; b < NUM_DECADES; b++) {
        if (decades[b].max_index > 2) {
            printf("  Range [%"PRIu64", %"PRIu64"): max index = %"PRIu64"\n",
                   decades[b].lo, decades[b].hi, decades[b].max_index);
        }
    }

    fclose(sf);
    printf("\n  Written to %s and %s\n", PRIMES_CSV, SUMMARY_CSV);
}

/* ═══════════════════════════════════════════════════════════════════
 * Main
 * ═══════════════════════════════════════════════════════════════════ */

int main(int argc, char **argv) {
    uint64_t pmax = 100000000ULL;  /* default 10^8 */
    int do_resume = 0;
    int do_convergents = 0;
    int do_multiscale = 0;
    int do_primes = 1;
    int explicit_min_index = 0;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--resume") == 0) {
            do_resume = 1;
        } else if (strcmp(argv[i], "--convergents") == 0) {
            do_convergents = 1;
            do_primes = 0;
        } else if (strcmp(argv[i], "--multiscale") == 0) {
            do_multiscale = 1;
            do_primes = 0;
        } else if (strcmp(argv[i], "--all") == 0) {
            do_convergents = 1;
            do_multiscale = 1;
            do_primes = 1;
        } else if (strcmp(argv[i], "--min-index") == 0 && i + 1 < argc) {
            min_index_csv = atoi(argv[++i]);
            if (min_index_csv < 1) min_index_csv = 1;
            explicit_min_index = 1;
        } else {
            /* Positional: P_MAX */
            char *end;
            uint64_t val = strtoull(argv[i], &end, 10);
            if (*end == '\0' && val >= 5) pmax = val;
        }
    }

    /* Auto-set min_index for large scans to avoid huge CSV */
    if (!explicit_min_index && pmax > 1000000000ULL)
        min_index_csv = 100;

    printf("╔══════════════════════════════════════════════════════════════╗\n");
    printf("║  Furstenberg ×2, ×3 Conjecture — Phase 1 Orbit Analysis   ║\n");
    printf("╚══════════════════════════════════════════════════════════════╝\n");

    init_small_primes();
    printf("  Small primes: %d (up to %u)\n", nsprimes, sprimes[nsprimes - 1]);

    if (do_convergents) {
        compute_convergents();
    }

    if (do_multiscale) {
        compute_multiscale();
    }

    if (do_primes) {
        run_prime_scan(pmax, do_resume);
    }

    if (sieve) free(sieve);
    if (prime_list) free(prime_list);

    printf("\nDone.\n");
    return 0;
}
